### ISSUE TITLE
AssertionError: Missing evaluation key. Patch RLlib as per the installation guide

### ISSUE THREAD

**Issue by forrestneo** [NeuralMMO/baselines#6]
Failure # 1 (occurred at 2022-04-25_11-36-54)
Traceback (most recent call last):
  File "/home/zsd/anaconda3/envs/nmmo/lib/python3.9/site-packages/ray/tune/trial_runner.py", line 893, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/zsd/anaconda3/envs/nmmo/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py", line 707, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/zsd/anaconda3/envs/nmmo/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/zsd/anaconda3/envs/nmmo/lib/python3.9/site-packages/ray/worker.py", line 1733, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): [36mray::PPO.train()[39m (pid=449, ip=172.22.54.224, repr=PPO)
  File "/home/zsd/nmmo/baselines/rllib_wrapper.py", line 243, in train
    stats = super().train()
  File "/home/zsd/anaconda3/envs/nmmo/lib/python3.9/site-packages/ray/tune/trainable.py", line 315, in train
    result = self.step()
  File "/home/zsd/anaconda3/envs/nmmo/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 982, in step
    raise e
  File "/home/zsd/anaconda3/envs/nmmo/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 963, in step
    step_attempt_results = self.step_attempt()
  File "/home/zsd/anaconda3/envs/nmmo/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 1066, in step_attempt
    step_results.update(self.evaluate())
  File "/home/zsd/nmmo/baselines/rllib_wrapper.py", line 253, in evaluate
    assert 'Raw_Policy_IDs' in stats, err
AssertionError: Missing evaluation key. Patch RLlib as per the installation guide

**Comment by forrestneo** [comment]
@jsuarez5341

**Comment by TheCrazyT** [comment]
@forrestneo https://neuralmmo.github.io/build/html/rst/landing.html#icon-installation

```
Required RLlib patch: 

Add 

 custom_metrics[k] = v_list;

continue after line 193 (175 pre-master) in your RLlib metrics file (usually ~/anaconda3/lib/python3.8/site-packages/ray/rllib/evaluation/metrics.py)

**Comment by forrestneo** [comment]
@TheCrazyT I have a try ,did not work.

**Comment by TheCrazyT** [comment]
@forrestneo 

Well I did not patch it as mentioned on that page, i placed the patch at the end of the loop:
```
for k, v_list in custom_metrics.copy().items():
        filt = [v for v in v_list if not np.any(np.isnan(v))]
        custom_metrics[k + "_mean"] = np.mean(filt)
        if filt:
            custom_metrics[k + "_min"] = np.min(filt)
            custom_metrics[k + "_max"] = np.max(filt)
        else:
            custom_metrics[k + "_min"] = float("nan")
            custom_metrics[k + "_max"] = float("nan")
        del custom_metrics[k]
        custom_metrics[k] = v_list
```

But it probably depends on the version.
